### ISSUE TITLE
Can't run debugger

### ISSUE THREAD

**Issue by mscheifer** [flathub/com.jetbrains.PyCharm-Community#566]
After upgrading to 2024.1.4 I can't run code in debug mode. I get this error:

```
Traceback (most recent call last):
  File "/app/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 59, in <module>
    from _pydevd_bundle.pydevd_trace_dispatch import (
ImportError: cannot import name 'trace_dispatch' from '_pydevd_bundle.pydevd_trace_dispatch' (/app/pycharm/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_trace_dispatch.py)

Process finished with exit code 1
```

**Comment by mscheifer** [comment]
I fixed this by uninstalling with `--delete-data` and reinstalling and re setting up my project.
